# Generated by Django 4.2.13 on 2024-08-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('merchant', models.CharField(max_length=255)),
                ('is_fraud', models.BooleanField(default=False)),
            ],
        ),
    ]
